### ISSUE TITLE
Object not found while deploying to Azure. 

### ISSUE THREAD

**Issue by unl1k3ly** [ralphte/build_a_phish#5]
Hi mate!

Nice project, thanks for that.

Could you please advice how to amend this error while deploying `Deploy Azure CDN` 

```fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'phish'"}```

Cheers

**Comment by heyquentin** [comment]
Try moving the Azure deployment to the last in the list

**Comment by adamsvoboda** [comment]
Moving the Azure deployment to the bottom of the list in the `phish_deploy.yml` file fixed the issue for me as well. Same issue above.

**Comment by vitorallo** [comment]
I don't get it, it's already the last one on the tasks loop, mailgun is commented out... ?!

**Comment by jafeather** [comment]
It looks like the inventory file is not being refreshed as expected. It looks like this should happen in roles/digitalocean/tasks/main.yml 

I was able to get passed this error by adding a new task for inventory refresh at the end of roles/digitalocean/tasks/droplet_deploy.yml:

- name: Refresh Inventory
  tags: [ never, phish ]
  meta: refresh_inventory
