### ISSUE TITLE
Configuration Misunderstanding

### ISSUE THREAD

**Issue by GeorgePatsias** [ralphte/build_a_phish#7]
Just wanted to make sure what to configure in:

- In the GoPhish > Campaigns > New Campaign > URL, which of the following shall I put? `company-www...`, `company-login...`, `company-loading...` or the IP of the DO Droplet?

- In the GoPhish > Landing pages > New Page, which site shall I import? `company-www...`, `company-login...`, `company-loading  ...` or something else? Also which redirector shall I define?

Thats all, thank you for your time and great project!

**Comment by srand2** [comment]
@GeorgePatsias did you figure this out? Im having the same misunderstanding. Would appreciate a little help here @ralphte 
Thanks!!

**Comment by GeorgePatsias** [comment]
No. The phislet o365 is not working

**Comment by srand2** [comment]
@GeorgePatsias ok. @ralphte can you confirm this?
