### ISSUE TITLE
Accessing Session Data on evilgnix

### ISSUE THREAD

**Issue by srand2** [ralphte/build_a_phish#9]
After capturing session data in logs Evilgnix2 usually presents the data in a clear and concise manner with the 'sessions' command. Is there a way to access the same presentation with this setup? 

**Steps I tried:**

I tried to enter docker -> `docker exec -t evilgnix2 sh`  and the run evilgnix2 from there but that didnt work.
I tried to manually piece together all the o365 data captured but its too big a mess.

**Comment by ralphte** [comment]
There are two ways. There not as good as sessions command but they work fine.`docker logs evilgnix2` will let you see this output. In addition in the /opt/docker/evilgix2 folder there should be a logs folder that has the logs as well.

**Comment by srand2** [comment]
ok thanks! @ralphte one more question while Im at it. Whats the purpose of the mailgun api? I didnt see how you used it on the webinar or in your documentation.
